---
- hosts: pixie
  become: yes
  vars_prompt:
    - name: domain
      prompt: What is the (internal) domain of pixie?
      private: no
      default: pixie.progcont
  tasks:
    - name: Install base
      apt:
        name: 
        - dnsmasq
        - ntpdate
        - git
        - apt-cacher-ng
        - ansible
        - nginx
        - gcc
        - binutils
        - make
        - perl
        - liblzma-dev
        - mtools
        - snapd
        state: latest
        cache_valid_time: 3600
    - name: Clone IPXE
      ansible.builtin.git:
        repo: 'git://git.ipxe.org/ipxe.git'
        dest: /pixie/repo
    - name: Setup IPXE scripts
      copy:
        dest: "/pixie/embed.ipxe"
        content: |
          #!ipxe
          dhcp

          set base-url {{ domain }}

          :retry
          echo Trying to load image
          imgload ${base-url}/img/linux
          echo Trying to load initrd
          initrd ${base-url}/img/initrd.gz

          echo Attempt boot
          imgargs linux auto=true fb=false url=${base-url}/setup/preseed interface=eth0 auto=true priority=critical net.ifnames=0 tasksel/first=\"\" hostname=teammachine domain=progcont

          boot || echo -n Failed
          menu Boot is not allowed or connection failed
           item --gap Recommended:
           item retry    Retry
           item force    Force image (NOT RECOMMENDED)
           item --gap Other
           item shell    Enter iPXE shell
           item boot     Reboot
           choose --default retry --timeout 10000 target && goto ${target}

          :boot
           reboot

          :shell
           shell


          :force
           chain ${base-url}/setup/force || goto retry
    - name: Build IPXE
      make:
        chdir: /pixie/repo/src/
        target: bin/undionly.kpxe
        params:
         EMBED: /pixie/embed.ipxe
      become: yes
    - name: Copy bootloader
      copy: 
        src: /pixie/repo/src/bin/undionly.kpxe
        remote_src: yes
        dest: /pixie/tftp/